"use client";

import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";
import CartProvider from "@/context/CartContext";
import { UserProvider } from "@/context/UserContext";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname();
  const isDashboard = pathName.startsWith("/dashboard");
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <CartProvider>
            {!isDashboard && <Header />}
            {children}
            {!isDashboard && <Footer />}
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
